In [2]:
#libraries
import pandas as pd
import numpy as np

## overview of SRTR data

#overview of SRTR data (This is the SRTR data /home/kidneyData/DATA_SP_2020) /home/kidneyData/DATA_SP_2020
cand_kipa
tx_ki
donor_deceased
rec_histo
Any additional tables as necessary to perform analysis

### cand_kipa

In [3]:
#candiadate info dataset
cand_kipa = pd.read_sas('/home/kidneyData/DATA_SP_2020/cand_kipa.sas7bdat')

In [4]:
cand_kipa.head()

,PERS_ID,PX_ID,WL_ORG,CAN_GENDER,CAN_ABO,CAN_RACE,CAN_RACE_SRTR,CAN_ETHNICITY_SRTR,DON_TY,REC_TX_PROCEDURE_TY,...,CAN_INIT_ACT_STAT_DT,CAN_INIT_INACT_STAT_DT,CAN_LAST_ACT_STAT_DT,CAN_LAST_INACT_STAT_DT,CAN_INIT_ACT_STAT_CD,PERS_NEXTTX,PERS_NEXTTX_TRR_ID,CAN_TRR_EXISTS,CAN_PAIRED_LIVE_DONOR_ID,DONOR_ID
0,3759020.0,-1987684.0,b'KI',b'M',b'A',8.0,b'WHITE',b'NLATIN',NaN,NaN,...,1990-09-12,NaT,1996-02-12,NaT,4010.0,2004-11-10,373530.0,0.0,NaN,NaN
1,3198556.0,-1988179.0,b'KI',b'M',b'O',8.0,b'WHITE',b'NLATIN',NaN,NaN,...,NaT,1987-12-28,NaT,1994-05-10,NaN,NaT,NaN,0.0,NaN,NaN
2,3147238.0,-1996997.0,b'KI',b'F',b'A',16.0,b'BLACK',b'NLATIN',NaN,NaN,...,1992-07-31,1994-11-08,1994-11-07,1995-03-06,4010.0,NaT,NaN,0.0,NaN,NaN
3,2599447.0,-1997894.0,b'KI',b'M',b'B',16.0,b'BLACK',b'NLATIN',NaN,NaN,...,1990-11-13,NaT,1997-07-11,NaT,4010.0,NaT,NaN,0.0,NaN,NaN
4,3257192.0,-1993947.0,b'KI',b'F',b'B',16.0,b'BLACK',b'NLATIN',NaN,NaN,...,1991-10-30,1994-04-15,1994-04-14,1994-10-19,4010.0,NaT,NaN,0.0,NaN,NaN

In [5]:
cand_kipa.shape

(961240, 195)

In [6]:
# list of all the features (column headers) of table
#list(cand_kipa.columns)

In [7]:
p=list(cand_kipa.columns)
result = [i for i in p if i.startswith('PX_ID')]
result

['PX_ID']

In [9]:
cand_kipa['DONOR_ID']

0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
            ...
961235    422460.0
961236    422374.0
961237    422247.0
961238    422228.0
961239    422329.0
Name: DONOR_ID, Length: 961240, dtype: float64

### tx_ki

In [8]:
#transplant info dataset
tx_ki = pd.read_sas('/home/kidneyData/DATA_SP_2020/tx_ki.sas7bdat')

In [26]:
tx_ki.head()

,ORG_TY,PERS_ID,REC_TX_DT,REC_POSTX_LOS,PX_ID,REC_A_MM_EQUIV_TX,REC_A_MM_EQUIV_CUR,REC_B_MM_EQUIV_TX,REC_B_MM_EQUIV_CUR,REC_DR_MM_EQUIV_TX,...,TFL_COD,PERS_RELIST,PERS_RETX,PERS_RETX_TRR_ID,TFL_LAFUDATE,REC_MM_EQUIV_TX,REC_MM_EQUIV_CUR,PERS_OPTN_COD,DONOR_ID,DONOR_ID_VESSEL
0,b'KI',4956632.0,2012-11-20,5.0,853031.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaT,NaT,NaN,2018-04-12,3.0,3.0,NaN,419584.0,NaN
1,b'KI',4787788.0,2012-10-19,5.0,736755.0,0.0,0.0,0.0,0.0,0.0,...,NaN,2013-08-21,NaT,NaN,2017-10-24,0.0,0.0,NaN,418721.0,NaN
2,b'KI',4059261.0,2012-09-30,6.0,575654.0,2.0,2.0,2.0,2.0,0.0,...,NaN,NaT,NaT,NaN,2017-02-09,4.0,4.0,NaN,417693.0,NaN
3,b'KI',4893631.0,2012-12-30,9.0,785678.0,1.0,1.0,2.0,2.0,2.0,...,NaN,2013-01-02,2018-02-07,773433.0,2013-01-08,5.0,5.0,NaN,422447.0,NaN
4,b'KI',4573989.0,2012-10-05,2.0,664555.0,1.0,1.0,2.0,2.0,1.0,...,NaN,NaT,NaT,NaN,2015-01-19,4.0,4.0,NaN,417628.0,NaN

In [27]:
tx_ki.shape

(469711, 285)

In [29]:
# Finding Common columns of cand_kipa and txf_ki using numpy
common_columns = np.intersect1d(cand_kipa.columns, tx_ki.columns)
print(common_columns)

['CAN_ABO' 'CAN_AGE_AT_LISTING' 'CAN_AGE_DIAB'
 'CAN_AGE_IN_MONTHS_AT_LISTING' 'CAN_ANGINA' 'CAN_ANGINA_CAD'
 'CAN_CEREB_VASC' 'CAN_CITIZENSHIP' 'CAN_DGN' 'CAN_DIAB' 'CAN_DIAB_TY'
 'CAN_DRUG_TREAT_COPD' 'CAN_DRUG_TREAT_HYPERTEN' 'CAN_EDUCATION'
 'CAN_ETHNICITY_SRTR' 'CAN_GENDER' 'CAN_HGT_CM' 'CAN_INIT_STAT'
 'CAN_LAST_STAT' 'CAN_LISTING_DT' 'CAN_MALIG' 'CAN_PEPTIC_ULCER'
 'CAN_PERIPH_VASC' 'CAN_PREV_HL' 'CAN_PREV_HR' 'CAN_PREV_IN' 'CAN_PREV_KI'
 'CAN_PREV_KI_TX_FUNCTN' 'CAN_PREV_KP' 'CAN_PREV_LI' 'CAN_PREV_LU'
 'CAN_PREV_PA' 'CAN_PREV_TX' 'CAN_PREV_TXFUS' 'CAN_PULM_EMBOL' 'CAN_RACE'
 'CAN_RACE_SRTR' 'CAN_REM_CD' 'CAN_SOURCE' 'CAN_TOT_ALBUMIN' 'CAN_WGT_KG'
 'DONOR_ID' 'DON_TY' 'ORG_AR' 'PERS_ID' 'PERS_OPTN_DEATH_DT'
 'PERS_RESTRICT_DEATH_DT' 'PERS_RESTRICT_DEATH_VRFY' 'PERS_SSA_DEATH_DT'
 'PX_ID' 'REC_TX_DT' 'REC_TX_PROCEDURE_TY']

In [31]:
#merge tables cand_kipa and tx_ki
cand_tx = cand_kipa.merge(tx_ki, left_index=True, right_index=True,
             on='PX_ID', suffixes=('', '_DROP')).filter(regex='^(?!.*_DROP)')

In [196]:
cand_tx.head()

,PERS_ID,PX_ID,WL_ORG,CAN_GENDER,CAN_ABO,CAN_RACE,CAN_RACE_SRTR,CAN_ETHNICITY_SRTR,DON_TY,REC_TX_PROCEDURE_TY,...,TFL_DEATH_DT,TFL_COD,PERS_RELIST,PERS_RETX,PERS_RETX_TRR_ID,TFL_LAFUDATE,REC_MM_EQUIV_TX,REC_MM_EQUIV_CUR,PERS_OPTN_COD,DONOR_ID_VESSEL
0,3759020.0,-1987684.0,b'KI',b'M',b'A',8.0,b'WHITE',b'NLATIN',NaN,NaN,...,NaT,NaN,NaT,NaT,NaN,2018-04-12,3.0,3.0,NaN,NaN
1,3198556.0,-1988179.0,b'KI',b'M',b'O',8.0,b'WHITE',b'NLATIN',NaN,NaN,...,NaT,NaN,2013-08-21,NaT,NaN,2017-10-24,0.0,0.0,NaN,NaN
2,3147238.0,-1996997.0,b'KI',b'F',b'A',16.0,b'BLACK',b'NLATIN',NaN,NaN,...,NaT,NaN,NaT,NaT,NaN,2017-02-09,4.0,4.0,NaN,NaN
3,2599447.0,-1997894.0,b'KI',b'M',b'B',16.0,b'BLACK',b'NLATIN',NaN,NaN,...,NaT,NaN,2013-01-02,2018-02-07,773433.0,2013-01-08,5.0,5.0,NaN,NaN
4,3257192.0,-1993947.0,b'KI',b'F',b'B',16.0,b'BLACK',b'NLATIN',NaN,NaN,...,NaT,NaN,NaT,NaT,NaN,2015-01-19,4.0,4.0,NaN,NaN

### donor_deceased

In [37]:
donor_deceased = pd.read_sas('/home/kidneyData/DATA_SP_2020/donor_deceased.sas7bdat')

In [38]:
donor_deceased.head()

,PERS_ID,DON_TY,DON_TX,DON_AGE_IN_MONTHS,DON_AGE,DON_GENDER,DON_HOME_STATE,DON_RACE,DON_RACE_SRTR,DON_ETHNICITY_SRTR,...,DON_TROPONIN_I,DON_TROPONIN_T,DON_LEFT_LUNG_PERFUSION,DON_RIGHT_LUNG_PERFUSION,DON_INTRACRANIAL_CANCER_TYPE,DON_EXTRACRANIAL_CANCER_TYPE,DON_SKIN_CANCER_TYPE,DON_PREV_GASTRO_DISEASE,DON_OPO_CTR_ID,DONOR_ID
0,8000000.0,b'C',6.0,9.0,0.0,b'M',b'OH',8.0,b'WHITE',b'NLATIN',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,530.0,100223.0
1,8000001.0,b'C',6.0,193.0,16.0,b'M',b'NM',2000.0,b'WHITE',b'LATINO',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,416.0,12687.0
2,8000002.0,b'C',6.0,480.0,40.0,b'M',b'NC',8.0,b'WHITE',b'NLATIN',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,390.0,187082.0
3,8000003.0,b'C',6.0,297.0,24.0,b'M',b'NC',16.0,b'BLACK',b'NLATIN',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,390.0,218478.0
4,8000004.0,b'C',6.0,195.0,16.0,b'F',b'AL',8.0,b'WHITE',b'NLATIN',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,76722.0

In [39]:
donor_deceased.shape

(224529, 256)

In [40]:
#list(donor_deceased.columns)

In [42]:
# Finding Common columns of cand_kipa and txf_ki using numpy
common_columns = np.intersect1d(cand_tx.columns, donor_deceased.columns)
print(common_columns)

['DONOR_ID' 'DON_A1' 'DON_A2' 'DON_ABO' 'DON_AGE' 'DON_AGE_IN_MONTHS'
 'DON_ANTI_CMV' 'DON_ANTI_HCV' 'DON_B1' 'DON_B2' 'DON_CAD_DON_COD'
 'DON_CARDIAC_ARREST_AFTER_DEATH' 'DON_CITIZENSHIP' 'DON_COD_DON_STROKE'
 'DON_CONT_CIGARETTE' 'DON_CONT_COCAINE' 'DON_CONT_IV_DRUG'
 'DON_CONT_OTHER_DRUG' 'DON_CREAT' 'DON_DDAVP' 'DON_DEATH_CIRCUM'
 'DON_DEATH_MECH' 'DON_DOBUTAMINE' 'DON_DOPAMINE' 'DON_DR1' 'DON_DR2'
 'DON_ETHNICITY_SRTR' 'DON_EXPAND_DON_KI' 'DON_GENDER' 'DON_HGT_CM'
 'DON_HIGH_CREAT' 'DON_HIST_CANCER' 'DON_HIST_CIGARETTE_GT20_PKYR'
 'DON_HIST_COCAINE' 'DON_HIST_DIAB' 'DON_HIST_HYPERTEN' 'DON_HIST_IV_DRUG'
 'DON_HIST_OTHER_DRUG' 'DON_HTN' 'DON_INOTROP_AGENT_GE3'
 'DON_INOTROP_SUPPORT' 'DON_LF_KI_BIOPSY' 'DON_LF_KI_PUMP'
 'DON_NON_HR_BEAT' 'DON_OPO_CTR_ID' 'DON_RACE' 'DON_RACE_SRTR'
 'DON_RECOV_DT' 'DON_RT_KI_BIOPSY' 'DON_RT_KI_PUMP' 'DON_TY'
 'DON_WARM_ISCH_TM_MINS' 'DON_WGT_KG' 'PERS_ID']

In [47]:
cand_tx_ddonor = cand_tx.merge(donor_deceased, left_index=True, right_index=True,
             on='DONOR_ID', suffixes=('', '_DROP')).filter(regex='^(?!.*_DROP)')

In [23]:
#cand_transplant_donordecease_merge.to_csv("cand_transplant_donordecease_merge.csv")

In [48]:
cand_tx_ddonor.head()

,PERS_ID,PX_ID,WL_ORG,CAN_GENDER,CAN_ABO,CAN_RACE,CAN_RACE_SRTR,CAN_ETHNICITY_SRTR,DON_TY,REC_TX_PROCEDURE_TY,...,DON_RACE_WHITE,DON_LEGALLY_BRAIN_DEAD,DON_TROPONIN_I,DON_TROPONIN_T,DON_LEFT_LUNG_PERFUSION,DON_RIGHT_LUNG_PERFUSION,DON_INTRACRANIAL_CANCER_TYPE,DON_EXTRACRANIAL_CANCER_TYPE,DON_SKIN_CANCER_TYPE,DON_PREV_GASTRO_DISEASE
0,3759020.0,-1987684.0,b'KI',b'M',b'A',8.0,b'WHITE',b'NLATIN',NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3198556.0,-1988179.0,b'KI',b'M',b'O',8.0,b'WHITE',b'NLATIN',NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3147238.0,-1996997.0,b'KI',b'F',b'A',16.0,b'BLACK',b'NLATIN',NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2599447.0,-1997894.0,b'KI',b'M',b'B',16.0,b'BLACK',b'NLATIN',NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3257192.0,-1993947.0,b'KI',b'F',b'B',16.0,b'BLACK',b'NLATIN',NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
#list(cand_transplant_donordecease_merge.columns)

In [50]:
#datanew= pd.read_csv("cand_transplant_donordecease_merge.csv")

### rec_histo

In [51]:
rec_histo = pd.read_sas('/home/kidneyData/DATA_SP_2020/rec_histo.sas7bdat')

In [52]:
rec_histo.head()

,REC_HISTO_TX_ID,REC_TX_DT,REC_LAB_CTR_CD,REC_LAB_CTR_TY,REC_ORIG_PROV,REC_HLA_TYP_DONE,REC_PRA_TEST_DONE,REC_XMATCH_DONE,REC_XMATCH_DONE_PERIOD,REC_DON_RETYP,...,T_CELL_DONE_XMAT_FLOW_CYTOMETRY,T_CELL_DONE_XMAT_SOLID_PHASE,B_CELL_DONE_XMAT_NO_AHG,B_CELL_DONE_XMAT_AHG,B_CELL_DONE_XMAT_FLOW_CYTOMETRY,B_CELL_DONE_XMAT_SOLID_PHASE,H_CELL_DONE_XMAT_NO_AHG,H_CELL_DONE_XMAT_AHG,H_CELL_DONE_XMAT_FLOW_CYTOMETRY,H_CELL_DONE_XMAT_SOLID_PHASE
0,225084.0,1998-03-19,b'CATL',b'TT1',NaN,b'Y',b'Y',b'Y',NaN,b'N',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1000001.0,1994-01-28,b'MIHF',b'IT1',b'230053',b'Y',b'Y',b'Y',NaN,b'N',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1000002.0,1994-01-29,b'OHUH',b'IT1',b'360137',b'Y',b'Y',b'Y',NaN,b'Y',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000003.0,1994-01-27,b'TXTX',b'IT1',b'450021',b'Y',b'Y',b'Y',NaN,b'Y',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1000004.0,1994-01-27,b'AZUA',b'IT1',b'030064',b'Y',b'Y',b'Y',NaN,b'N',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
rec_histo.shape

(748501, 111)

In [54]:
#list(rec_histo.columns)

In [27]:
# Finding Common columns of cand_tx_ddonor and rec_histo using numpy
common_columns3 = np.intersect1d(cand_tx_ddonor, rec_histo.columns)
print(common_columns3)

['DON_A1' 'DON_A2' 'DON_B1' 'DON_B2' 'DON_BW4' 'DON_BW6' 'DON_DR1'
 'DON_DR2' 'REC_A1' 'REC_A2' 'REC_B1' 'REC_B2' 'REC_DR1' 'REC_DR2'
 'REC_HISTO_TX_ID' 'REC_PRA_MOST_RECENT' 'REC_TX_DT']

In [33]:
z=list(cand_transplant_donordecease_merge.columns)
result = [i for i in z if i.startswith('TX_ID')]
result

['TX_ID']

In [108]:
x=list(rec_histo.columns)
result = [i for i in x if i.startswith('DONOR')]
result

[]

In [55]:
#data2 = pd.merge(cand_transplant_merge, donor_deceased, on='DONOR_ID')
cand_tx_ddonor_rec = cand_tx_ddonor.merge(rec_histo, left_index=True, right_index=True,
             left_on='TX_ID',right_on='REC_HISTO_TX_ID', suffixes=('', '_DROP')).filter(regex='^(?!.*_DROP)')

In [56]:
cand_tx_ddonor_rec.head()

,PERS_ID,PX_ID,WL_ORG,CAN_GENDER,CAN_ABO,CAN_RACE,CAN_RACE_SRTR,CAN_ETHNICITY_SRTR,DON_TY,REC_TX_PROCEDURE_TY,...,T_CELL_DONE_XMAT_FLOW_CYTOMETRY,T_CELL_DONE_XMAT_SOLID_PHASE,B_CELL_DONE_XMAT_NO_AHG,B_CELL_DONE_XMAT_AHG,B_CELL_DONE_XMAT_FLOW_CYTOMETRY,B_CELL_DONE_XMAT_SOLID_PHASE,H_CELL_DONE_XMAT_NO_AHG,H_CELL_DONE_XMAT_AHG,H_CELL_DONE_XMAT_FLOW_CYTOMETRY,H_CELL_DONE_XMAT_SOLID_PHASE
0,3759020.0,-1987684.0,b'KI',b'M',b'A',8.0,b'WHITE',b'NLATIN',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3198556.0,-1988179.0,b'KI',b'M',b'O',8.0,b'WHITE',b'NLATIN',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3147238.0,-1996997.0,b'KI',b'F',b'A',16.0,b'BLACK',b'NLATIN',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2599447.0,-1997894.0,b'KI',b'M',b'B',16.0,b'BLACK',b'NLATIN',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3257192.0,-1993947.0,b'KI',b'F',b'B',16.0,b'BLACK',b'NLATIN',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
cand_tx_ddonor_rec.shape

(224529, 724)

In [59]:
cand_tx_ddonor_rec.to_csv("cand_tx_ddonor_rec.csv")

In [62]:
dataset_deceased=pd.read_csv('cand_tx_ddonor_rec.csv', low_memory=False)
dataset_deceased.head()

,Unnamed: 0,PERS_ID,PX_ID,WL_ORG,CAN_GENDER,CAN_ABO,CAN_RACE,CAN_RACE_SRTR,CAN_ETHNICITY_SRTR,DON_TY,...,T_CELL_DONE_XMAT_FLOW_CYTOMETRY,T_CELL_DONE_XMAT_SOLID_PHASE,B_CELL_DONE_XMAT_NO_AHG,B_CELL_DONE_XMAT_AHG,B_CELL_DONE_XMAT_FLOW_CYTOMETRY,B_CELL_DONE_XMAT_SOLID_PHASE,H_CELL_DONE_XMAT_NO_AHG,H_CELL_DONE_XMAT_AHG,H_CELL_DONE_XMAT_FLOW_CYTOMETRY,H_CELL_DONE_XMAT_SOLID_PHASE
0,0,3759020.0,-1987684.0,b'KI',b'M',b'A',8.0,b'WHITE',b'NLATIN',NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,3198556.0,-1988179.0,b'KI',b'M',b'O',8.0,b'WHITE',b'NLATIN',NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,3147238.0,-1996997.0,b'KI',b'F',b'A',16.0,b'BLACK',b'NLATIN',NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2599447.0,-1997894.0,b'KI',b'M',b'B',16.0,b'BLACK',b'NLATIN',NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,3257192.0,-1993947.0,b'KI',b'F',b'B',16.0,b'BLACK',b'NLATIN',NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:

dataset_deceased.drop(dataset_deceased.columns[[0]], axis = 1, inplace = True)

In [66]:
dataset_deceased.head()

,PERS_ID,PX_ID,WL_ORG,CAN_GENDER,CAN_ABO,CAN_RACE,CAN_RACE_SRTR,CAN_ETHNICITY_SRTR,DON_TY,REC_TX_PROCEDURE_TY,...,T_CELL_DONE_XMAT_FLOW_CYTOMETRY,T_CELL_DONE_XMAT_SOLID_PHASE,B_CELL_DONE_XMAT_NO_AHG,B_CELL_DONE_XMAT_AHG,B_CELL_DONE_XMAT_FLOW_CYTOMETRY,B_CELL_DONE_XMAT_SOLID_PHASE,H_CELL_DONE_XMAT_NO_AHG,H_CELL_DONE_XMAT_AHG,H_CELL_DONE_XMAT_FLOW_CYTOMETRY,H_CELL_DONE_XMAT_SOLID_PHASE
0,3759020.0,-1987684.0,b'KI',b'M',b'A',8.0,b'WHITE',b'NLATIN',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3198556.0,-1988179.0,b'KI',b'M',b'O',8.0,b'WHITE',b'NLATIN',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3147238.0,-1996997.0,b'KI',b'F',b'A',16.0,b'BLACK',b'NLATIN',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2599447.0,-1997894.0,b'KI',b'M',b'B',16.0,b'BLACK',b'NLATIN',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3257192.0,-1993947.0,b'KI',b'F',b'B',16.0,b'BLACK',b'NLATIN',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
dataset_deceased.shape

(224529, 724)